name: Joo kadena mining club 🤷‍♂️
description: Got a question about multitoolbox, deployment, development or usage?
title: '[QUESTION] DOS'NODE
labels: ['🤷‍♂️]

body:
  # Filed 1 - Intro Text
  - type: markdown
    attributes:
      value: >
        Thanks for using multitoolbox! Questions are welcome.
        Quick questions should be asked in the [Official RunOnFlux Discord](https://discord.io/runonflux) support channels, Please. :)
    validations:
      required: false

  # Field 2 - The actual question
  - type: I am receiving DOS on mijn flux wallet app. There for i cant mine any flux. 
    id: How can i get my Node miner started? 
    attributes:
      label: Question
      description: Outline your question in a clear and concise manner
    validations:
      required: true

  # Field 3 - Category
  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What part of the application does this relate to?
      options:
       
        - Option 3
  
    validations:
      required: true

  # Field 4 - User has RTFM first, and agrees to code of conduct, etc
  - type: checkboxes
    id: idiot-check
    attributes:
      label: Please tick the boxes
      description: Before submitting, please ensure that
      options:
        - label: You have explained the issue clearly, and included all relevant info
          required: true
        - label: You are using the latest version of multitoolbox
          required: true
        - label: You've checked that this [issue hasn't already been raised](https://github.com/RunOnFlux/fluxnode-multitool/issues?q=is%3Aissue)
          required: true
        - label: You've checked the official [RunOnFlux Discord](https://discord.io/runonflux) Pinned messages and FAQ ![important](https://img.shields.io/badge/Important!-F6094E)
          required: true
        - label: You agree to the [code of conduct](https://github.com/RunOnFlux/fluxnode-multitool/blob/master/.github/CODE_OF_CONDUCT.md)
          required: true
